services:
  frontend:
    image: 005208535800.dkr.ecr.us-west-2.amazonaws.com/rails-nginx
    x-ecr:
      InterpolateWithDigest: true

x-dns:
  PublicZone:
    Name: danbradbury.net
  PrivateNamespace:
    Name: cluster.internal
#x-elbv2:
#  public-alb:
#    Properties:
#      Scheme: internet-facing
#      Type: application
#    Services:
#      - name: frontend:frontend
#        port: 80
#        protocol: HTTP
#    Listeners:
#      - Port: 80
#        Protocol: HTTP
#        Targets:
#          - name: frontend:frontend
#            access: /
