services:
  #nginx:
  #  x-network:
  #    AssignPublicIp: true
  #  image: nginx
  #  volumes:
  #    - type: bind
  #      source: ./nginx/nginx.conf
  #      target: /etc/nginx/conf.d/default.conf
  #      read_only: true
  #  ports:
  #    - 80:80
  #  depends_on:
  #    - web
  web:
    image: uobradbury/rails
    x-network:
      AssignPublicIp: true
    build:
      context: .
      dockerfile: ./Dockerfile
    #command: bash -c "rm -f tmp/pids/server.pid && RAILS_ENV=development bundle exec rails s -p 3000 -b '0.0.0.0'"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256MB
    ports:
      - "3000:3000"
